/** @format */

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { UserWrapper } from "@/contexts/userContext";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserWrapper>
          <div className="bg-[#F1EFEB]">
            <Navbar />
            {children}
            <Toaster />
          </div>
        </UserWrapper>
      </body>
    </html>
  );
}
