/** @format */

import { Montserrat } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";
import { UserWrapper } from "@/contexts/userContext";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/components/footer";
const Navbar = dynamic(() => import("@/components/navbar"), { ssr: false });

// Configure the Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Add any weights you plan to use
});

export const metadata = {
  title: "Orchid Oasis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <UserWrapper>
          <div className="bg-[#f1faff] selection:bg-blue-200">
            <Navbar />
            {children}
            <Footer />
            <Toaster />
          </div>
        </UserWrapper>
      </body>
    </html>
  );
}
